In [2]:
from sklearn.datasets import make_blobs

In [18]:
X, y = make_blobs(n_samples=10, centers=3, n_features=1, random_state=42)
y , X

(array([0, 1, 1, 2, 2, 2, 1, 0, 0, 0]),
 array([[-2.19029544],
        [ 8.48911632],
        [ 8.43340799],
        [ 2.02732982],
        [ 5.59024852],
        [ 3.715796  ],
        [ 8.44290596],
        [-1.49868234],
        [-2.23015633],
        [-3.62107774]]))

In [1]:
from sklearn.datasets import load_iris
data = load_iris()
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [4]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
data.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [1]:
data = [{'#courses_opted': 4, 'GPA': 6.7},{'#courses_opted': 4, 'GPA': 8.5},
         {'#courses_opted': 2, 'GPA': 8.1},{'#courses_opted': 1, 'GPA': 7.2}, 
         {'#courses_opted': 1, 'GPA': 9.1}]

from sklearn.feature_extraction import DictVectorizer 
dv = DictVectorizer(sparse=False)
data_transformed = dv.fit_transform(data)
data_transformed[:2]

array([[4. , 6.7],
       [4. , 8.5]])

In [3]:
data_transformed

array([[4. , 6.7],
       [4. , 8.5],
       [2. , 8.1],
       [1. , 7.2],
       [1. , 9.1]])

In [11]:
data_transformed[:2]

array([[4. , 6.7],
       [4. , 8.5]])

In [3]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

X = np.array([[1], [2], [3]])
ft = FunctionTransformer(np.log)
ft.fit_transform(X)

array([[0.        ],
       [0.69314718],
       [1.09861229]])

In [5]:
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer

# Sample dataset
df = pd.DataFrame({'feature': [1, 4, 9, 16]})

# Define a square root transformation function
sqrt_transformer = FunctionTransformer(np.sqrt)

# Create a pipeline with the transformer
pipeline = Pipeline([
    ('sqrt_transform', sqrt_transformer)
])

# Transform the data
transformed_data = pipeline.fit_transform(df)
transformed_data


feature
0      1.0
1      2.0
2      3.0
3      4.0

In [7]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer

# Define a transformation function
log_transformer = FunctionTransformer(np.log1p, validate=True)

# Sample data
X = np.array([[0], [1], [2], [3]])

# Transform the data
X_transformed = log_transformer.transform(X)
X_transformed

array([[0.        ],
       [0.69314718],
       [1.09861229],
       [1.38629436]])

In [12]:
import itertools
import numpy as np

class PolynomialFeatures:
    def __init__(self, degree=2, include_bias=True):
        self.degree = degree
        self.include_bias = include_bias

    def fit_transform(self, X):
        # Ensure X is a NumPy array
        X = np.asarray(X)
        
        if X.ndim == 1:
            X = X[:, np.newaxis]
        
        n_samples, n_features = X.shape

        # Generate all possible combinations of feature indices with repetition
        combinations = []
        for d in range(0 if self.include_bias else 1, self.degree + 1):
            combinations.extend(itertools.combinations_with_replacement(range(n_features), d))
        
        # Generate the polynomial features
        poly_features = []
        for comb in combinations:
            poly_features.append(np.prod(X[:, comb], axis=1))
        
        return np.array(poly_features).T

# Example usage
X = np.array([[2, 3], [4, 5]])
poly = PolynomialFeatures(degree=2, include_bias=True)
transformed_X = poly.fit_transform(X)

print("Input:")
print(X)
print("\nTransformed:")
print(transformed_X)

Input:
[[2 3]
 [4 5]]

Transformed:
[[ 1  2  3  4  6  9]
 [ 1  4  5 16 20 25]]


In [12]:
from sklearn.preprocessing import OneHotEncoder
X = np.array([[4], [3], [2], [3], [1]])
ohe = OneHotEncoder()
ohe.fit_transform(X).toarray()

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]])

## One hot encode Implemented!

In [23]:
X = np.array([[4], [3], [2], [3], [1]])
matrix = []
for i in range(len(X)):
    entry = X[i][0]
    curr_row = []
    for j in range(1,max(X)[0]+1):
        if j == entry:
            curr_row.append(1)
        else:
            curr_row.append(0)
    matrix.append(curr_row)
    
print(np.array(matrix))
    

[[0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 1 0]
 [1 0 0 0]]


In [29]:
from sklearn.preprocessing import MultiLabelBinarizer

# Input: list of sets (multi-labels)
X = [
    {'Heart-disease', 'Diabetes'},
    {'High-BP'},
    {'Heart-disease', 'High-BP'},
    {'Diabetes'}
]

# Initialize the MultiLabelBinarizer
mlb = MultiLabelBinarizer(classes=['Heart-disease', 'High-BP','Diabetes'])

# Fit and transform the data
X_transformed = mlb.fit_transform(X)

# Print the transformed matrix
print("Transformed Matrix (X'):")
print(X_transformed)

# Get the labels (column names)
print("\nLabels (Columns):")
print(mlb.classes_)

# Identify the column corresponding to 'Diabetes'
diabetes_column = list(mlb.classes_).index('Diabetes')
print("\nThe column corresponding to 'Diabetes' is:", diabetes_column)

Transformed Matrix (X'):
[[1 0 1]
 [0 1 0]
 [1 1 0]
 [0 0 1]]

Labels (Columns):
['Heart-disease' 'High-BP' 'Diabetes']

The column corresponding to 'Diabetes' is: 2


In [28]:
mlb.classes_

array(['Heart-desease', 'High-BP', 'Diabetes'], dtype=object)